/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114438-gea2e0e92ed-20240326"
#endif /* AVUTIL_FFVERSION_H */
